[mapping]
eursusd="USDC+EURS"
cvxeth="WETH+CVX"
teth="WETH+T"
cvxcrv="CRV+cvxCRV"
fpifrax="FRAX+FPI"
cvxfxs="FXS+cvxFXS"
f-usdd3crv="USDD+3Crv"
f-fraxbpape="ApeUSD+FRAXBP"
f-fraxbpbusd="BUSD+FRAXBP"
dola="DOLA+3Crv"
aleth="ETH+alETH"
frax="FRAX+3Crv"
2pool-frax="FRAX+USDC"
f-fraxbpgusd="GUSD+FRAXBP"
f-fraxbplusd="LUSD+FRAXBP"
ousd="OUSD+3Crv"
f-pusd="PUSd+3Crv"
tusd="TUSD+3Crv"
f-fraxbptusd="TUSD+FRAXBP"
f-fraxbpusdd="USDD+FRAXBP"
alusd="alUSD+3Crv"
f-fraxbpalusd="alUSD+FRAXBP"
musd="mUSD+3Crv"
f-fraxbpsusd="sUSD+FRAXBP"
xdai-f-x3CRV-gauge="xdai-WXDAI+USDC+USDT"

[groups]

fraxbp=[
    "ALCX+FRAXBP",
    "ApeUSD+FRAXBP",
    "BADGER+FRAXBP",
    "BUSD+FRAXBP",
    "CVX+FRAXBP",
    "DOLA+FRAXBP",
    "GUSD+FRAXBP",
    "LUSD+FRAXBP",
    "MAI+FRAXBP",
    "PUSd+FRAXBP",
    "RSR+FRAXBP",
    "SDT+FRAXBP",
    "TUSD+FRAXBP",
    "USDD+FRAXBP",
    "XAI+FRAXBP",
    "agEUR+FRAXBP",
    "alUSD+FRAXBP",
    "cvxCRV+FRAXBP",
    "cvxFXS+FRAXBP",
    "sUSD+FRAXBP",
]

3crv = [
    "DOLA+3Crv",
    "FRAX+3Crv",
    "OUSD+3Crv",
    "PUSd+3Crv",
    "TUSD+3Crv",
    "USDD+3Crv",
    "alUSD+3Crv",
    "mUSD+3Crv",
    "xdai-WXDAI+USDC+USDT",
    "fantom-f-g3CRV-gauge",
    "lusd",
    "mim",
    "rai",
    "usdm",
    "usdn",
    "usdp",
    "ust-wormhole",
]

eth = [
    "ETH+alETH", 
    "ETH+frxETH", 
    "reth", 
    "steth", 
]